# Generated by Django 4.0.3 on 2022-03-15 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLogin', '0002_alter_perfil_imagenperfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='imagenPerfil',
            field=models.ImageField(default='PorDefecto/profileImageDefault.jpg', null=True, upload_to='avatares'),
        ),
    ]
