# Generated by Django 4.0.3 on 2022-03-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_categoria_post_imagenpost_post_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagenPost',
            field=models.ImageField(default='PorDefecto/profileImageDefault.jpg', max_length=255, null=True, upload_to='imagenes'),
        ),
    ]
