# Generated by Django 4.0.3 on 2022-03-15 18:20

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_imagenpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuienSoy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, unique=True)),
                ('contenido', ckeditor_uploader.fields.RichTextUploadingField()),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('imagenQuienSoy', models.ImageField(default='PorDefecto/profileImageDefault.jpg', max_length=255, null=True, upload_to='imagenes')),
            ],
            options={
                'ordering': ['-creado_el'],
            },
        ),
    ]
